image: node:latest

stages:
    - build
    - test

test:
  stage: test
  before_script:
    - npm install --silent
  script: 
    - npm run test
    - npm run e2e

build:
  stage: build
  script: ng build
  artifacts:
    name: "project-$CI_COMMIT_REF_NAME"
    paths:
      - dist/
  only:
    - tags

