name: Staging Deployment

on:
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run:  docker build -t digitalexcellence/stagingfrontend .
      - name: Docker login
        run:  docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push images to Dockerhub 
        run: docker push digitalexcellence/stagingfrontend
      - name: Push to server
        uses: appleboy/ssh-action@master
        with: 
          host: ${{ secrets.STAGING_VPS_IP }}
          username: ${{ secrets.STAGING_VPS_USERNAME }}
          password: ${{ secrets.STAGING_VPS_PASSWORD }}
          script: cd ~/docker_compose && docker-compose down && docker-compose pull && docker-compose up -d